In [2]:
import torch

#### **Getting Started**

- torch.arange()

- tensor.numel(), torch.numel(tensor), len

- tensor.shape(), tensor.reshape()

- torch.zeros(), torch.ones()

- torch.randn()

- torch.tensor()

In [2]:
x = torch.arange(12, dtype= torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [8]:
length1 = len(x)
length2 = torch.numel(x)
length3 = x.numel()
print(length1)
print(length2)
print(length3)

12
12
12


In [10]:
shapeX = x.shape
print(shapeX)

torch.Size([12])


In [13]:
X_reshape = x.reshape(3, -1)
print(X_reshape)
X_reshape = x.reshape(-1, 4)
print(X_reshape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [14]:
X_zeros = torch.zeros(2,3,4)
print(X_zeros)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [17]:
X_ones = torch.ones(2,3,4)
print(X_ones)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [18]:
# random from Gaussian Distribution

X_randn = torch.randn(2,3,4)
print(X_randn)

tensor([[[-0.3285,  0.3127, -0.4224, -0.6867],
         [-0.5914, -0.9142,  0.0121,  0.3244],
         [-0.4061,  0.4734, -0.1230, -1.0347]],

        [[-0.7303,  0.0703, -0.9952, -0.1822],
         [ 0.2571,  0.5507, -0.4462, -0.4248],
         [-0.4661, -0.7054, -0.1217, -0.3676]]])


In [21]:
# create tensor from list

X_tensor = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(X_tensor)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


#### **Slicing and Indexing**

In [5]:
# create tensor
X = torch.arange(16, dtype = torch.float32)
X = X.reshape(-1,4)

print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


In [8]:
print(X[-1])
print(X[1,3])
print(X[:2,:2])

tensor([12., 13., 14., 15.])
tensor(7.)
tensor([[0., 1.],
        [4., 5.]])


#### **Operations**
- elementwise operator: 
    + apply the function to all element of tensor
    + we can create elementwise operator function by ourselves if the function maps from scalar to scalar
    + unary scalar f: R -> R, for example: exp
    + binary scalar f: R(d), R(d) -> R(d), for examples: __+, -, *, /, %, //__
- concatenation:
    + group tensor to a List or Tuple, then pass it to the **torch.cat()** function as the parameter
    + base on dim
- logical operator:
    + equal: **==**, compare all elements in the same position
- R -> 1:
    + sum, mean, ...

**List of function and method**:
- torch.cat()
- operator
- sum(), mean()

In [10]:
print(X)

X_exp = torch.exp(X) ## e^x
print(X_exp)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04],
        [1.6275e+05, 4.4241e+05, 1.2026e+06, 3.2690e+06]])


In [16]:
Y = torch.arange(16,dtype = torch.float32).reshape(-1, 4)
print(Y)
print(f"X + Y = {X + Y}")
print(f"X - Y = {X - Y}")
print(f"X * Y = {X * Y}")
print(f"X / Y = {X / Y}")
print(f"X ** Y = {X ** Y}")

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
X + Y = tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.]])
X - Y = tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
X * Y = tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.]])
X / Y = tensor([[nan, 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
X ** Y = tensor([[1.0000e+00, 1.0000e+00, 4.0000e+00, 2.7000e+01],
        [2.5600e+02, 3.1250e+03, 4.6656e+04, 8.2354e+05],
        [1.6777e+07, 3.8742e+08, 1.0000e+10, 2.8531e+11],
        [8.9161e+12, 3.0288e+14, 1.1112e+16, 4.3789e+17]])


In [25]:
concat_0 = torch.cat([X, Y], dim = 0)
print(concat_0)
concat_1 = torch.cat([X,Y], dim = 1)
print(concat_1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 12., 13., 14., 15.]])


In [26]:
print(X == Y)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [28]:
print(X.sum())
print(X.mean())

tensor(120.)
tensor(7.5000)


#### Broadcasting

If two tensor are not in the same size, under some conditions, the operators still can be used.
In the case when d = 1 in row or column, the elements will be duplicated so that tensors become the same size matrixs.

For example, 3x1 : [0,1,2] -> [[0,1,2], [0,1,2]] -> [[0,0],[1,1],[2,2]] and 1x2: [[0,1]] -> [[0,1],[0,1],[0,1]]

In [34]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
print(a+b)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


#### Saving memory

When we give a variable new result, first the result will be allocate to new memory, then varible point to this memory.
We can clearly understand when see the code above.

In [38]:
## before and after is not the same, which mean Y has point to new memory block.
Y = 3
before = id(Y)
Y = 3
after = id(Y)
print(before == after)

Y = 4
after = id(Y)
print(before == after)

True
False


**The main problems**

- In machine learning:
    + we dont want to allocate memory unnecessarily
    + we have hundred of megabytes of param and update them many times per second -> we want to update them inplace rather than allocate more memory
    + same parameters can be pointed by multiple variables. If we dont update inplace, we may be update all the references, which means allocate new memory for all references that leads to memory leaks.

**Solve the problem**

- using slice: Y[:] = <expression\>
- If we want to change the value, we can:
    + use X[:] = X operator Y (X[:] = X + Y)
    + use X operator= number (X += 3)

In [40]:
Y = torch.arange(10)
Z = torch.zeros_like(Y) ## zeros with the same shape as Y

before = id(Z)
Z[:] = Y*2
after = id(Z)

print(before == after)

True


In [42]:
before = id(Z)
Z[:] = Z + Y
after = id(Z)
print(before == after)

True


In [41]:
before = id(Z)
Z += 3
after = id(Z)
print(before == after)

True


#### Object Conversion

- Conversion with numpy:
    + tensor = torch.tensor(numpy_array) (also with list, tuple)
    + tensor = torch.from_numpy(numpy_array)
    + numpy_array = tensor.numpy()

In [48]:
import numpy as np

a = np.arange(10)
tensor1 = torch.tensor(a)
tensor2 = torch.from_numpy(a)
print(tensor1)
print(tensor2)
print(tensor1.numpy())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
[0 1 2 3 4 5 6 7 8 9]


- Convert size-1 tensor to number
    + we have tensor, we directly cast (if we know the type we want to cast) or use tensor.item(), then cast value

In [55]:
x = torch.tensor(1.5)
print(int(x))
print(float(x))
print(x.item())

1
1.5
1.5


#### Excercise
 1. Run the code in this section. Change the conditional statement X == Y to X < Y or X >
 Y, and then see what kind of tensor you can get.
 2. Replace the two tensors that operate by element in the broadcasting mechanism with
 other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [65]:
# after many tests, it bases on the size of matrix
a = torch.arange(3).reshape(1,3,1)
b = torch.arange(2).reshape(1,1,2)
print(a+b)

tensor([[[0, 1],
         [1, 2],
         [2, 3]]])
